apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-financedc-deployment
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: financedc
  template:
    metadata:
      labels:
        app: financedc
    spec:
      containers:
      - name: mytestdckube
        image: 31financehjtestacr.azurecr.io/test:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: financedc
    k8s-app: financedc
  name: financedc
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: financedc